language: node_js
node_js:
- 'lts/*'
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: MtfFAqnF2rHcjBuAormr2/UGL4av7d7PJxsO3Fl6ngrvYgIr4aPgvu/uXU+36id6HYcNTd1dyPB8qime7sPay5q2yRCQEuihB1NajOT9omtgReLXiTWn3BSU9crhTR9ZcpG0B6E3HWTKFy3OzHqUHrcSmPSG6HR+IksLN4XmRlg=
  on:
    tags: true
    repo: noflo/noflo-knex
