language: node_js
node_js:
- '4.6'
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: agLcLABLrMRF5QK5tzcaGAOEk9PRtOcJUsIrWseNJltGdsrEnWzGbPpQvdU3tCBzPYaor+BYQfZVLfRRUA51m1PHvB8SCEpPUjXaz+ZTSF8bHz3lEWdlwXFh6PQ1HiAGhwYsvCjcWjQucviYrGwIgzzTsJmZfb/tNtc/zmLKNEU=
  on:
    tags: true
    repo: noflo/noflo-knex
